// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RailFactory.Tenancy.Api.Infrastructure.Persistence;

#nullable disable

namespace RailFactory.Tenancy.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TenancyDbContext))]
    [Migration("20260601125156_AddTenantIntegrations")]
    partial class AddTenantIntegrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RailFactory.Tenancy.Api.Infrastructure.Persistence.TenantIntegrationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("CredentialsDek")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("credentials_dek");

                    b.Property<byte[]>("CredentialsIv")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("credentials_iv");

                    b.Property<byte[]>("EncryptedCredentials")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_credentials");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("provider_type");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Category")
                        .IsUnique()
                        .HasDatabaseName("uix_tenant_integrations_tenant_category");

                    b.ToTable("tenant_integrations", (string)null);
                });

            modelBuilder.Entity("RailFactory.Tenancy.Api.Infrastructure.Persistence.TenantRecord", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("ConnectionStrings")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("connection_strings");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Code");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_tenants_status");

                    b.ToTable("tenants", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
