// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RailFactory.Iam.Api.Infrastructure.Auth.Persistence;

#nullable disable

namespace RailFactory.Iam.Api.Infrastructure.Auth.Persistence.Migrations
{
    [DbContext(typeof(IamAuthDbContext))]
    [Migration("20260503121414_LegacyTenantCodeCleanup")]
    partial class LegacyTenantCodeCleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RailFactory.Iam.Api.Infrastructure.Auth.Persistence.IamLocalUserRecord", b =>
                {
                    b.Property<string>("ExternalProvider")
                        .HasColumnType("text")
                        .HasColumnName("external_provider");

                    b.Property<string>("ExternalSubject")
                        .HasColumnType("text")
                        .HasColumnName("external_subject");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("FirstLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_login_at");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ExternalProvider", "ExternalSubject");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_iam_local_users_email");

                    b.ToTable("iam_local_users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
